server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/houwanle/spring-cloud-config.git  #gittee上的仓库名称
          username: houwanle
          password: 账号密码
          # 搜索目录
          search-paths:
            - spring-cloud-config
      #读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

  rabbitmq:
    host: localhost    #15672 是管理界面的端口  5672是连接mq的端口
    port: 5672
    username: guest
    password: guest

