server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

# consul注册中心地址
  cloud:
    consul:
      host: 8.140.134.167
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}